F #-: Lithops appliance
OpenNebula/one-apps pull request #112
Opened 2024-06-05 13:07 UTC by Aletibazo

Created new appliance for Lithops in the appliances/Community folder, to be included on the Community Marketplace.

This appliance installs Lithops v3.4.0 on Ubuntu 22.04, with Docker v5:26.1.3-1. It has support for localhost compute backend and localhost / minio storage backend

2024-06-05 13:51 UTC, tinova approved these changes

2024-06-06 08:16 UTC, sk4zuzu requested changes

2024-06-06 08:16 UTC, sk4zuzu commented on appliances/Community/Lithops/appliance.sh
> +    return $?
```suggestion
    return 0
```

or I think the whole return statement can be just removed :thinking:

2024-06-06 08:16 UTC, sk4zuzu commented on appliances/Community/Lithops/appliance.sh
> +    [ -z "$ONEAPP_MINIO_ENDPOINT" ] && return 1
For consistency:

```suggestion
    [[ -z "$ONEAPP_MINIO_ENDPOINT" ]] && return 1
```

also in other lines in this function.

2024-06-06 08:16 UTC, sk4zuzu commented on appliances/Community/Lithops/appliance.sh
> +ONEAPP_BACKEND="${ONEAPP_BACKEND:-localhost}"
Maybe ONEAPP_BACKEND and ONEAPP_STORAGE could be called something like ONEAPP_LITHOPS_BACKEND and ONEAPP_LITHOPS_STORAGE, so later when somebody configures this in for example a flow service (with other apps), there are no name conflicts? :thinking:

2024-06-06 08:16 UTC, sk4zuzu commented on appliances/Community/Lithops/appliance.sh
> +service_configure()
I'm not sure what exactly gets executed, so docker is installed, some pip packages, but how and where all this is used? :)

2024-06-06 09:15 UTC, sk4zuzu approved these changes

2024-06-10 12:40 UTC, closed without merging