F #-: Add support for Multi-Node deployment
OpenNebula/one-apps pull request #125
Opened 2024-08-08 12:53 UTC by Aletibazo

2024-08-09 16:38 UTC, sk4zuzu requested changes

2024-08-09 16:38 UTC, sk4zuzu commented on appliances/MinIO/appliance.sh
> +        local_subdomain=$(awk -F. '{ print $1 }' <<<${ONEAPP_MINIO_HOSTNAME})
```suggestion
        local_subdomain=$(awk -F. '{ print $1 }' <<< "$ONEAPP_MINIO_HOSTNAME")
```

2024-08-09 16:38 UTC, sk4zuzu commented on appliances/MinIO/appliance.sh
> +        local_domain=$(sed -e "s/[^.]*//" <<<"$ONEAPP_MINIO_HOSTNAME")
```suggestion
        local_domain=$(sed -e "s/[^.]*//" <<< "$ONEAPP_MINIO_HOSTNAME")
```

2024-08-09 16:38 UTC, sk4zuzu commented on appliances/MinIO/appliance.sh
> +        local_nodes=($(onegate service show --json | jq -r '.SERVICE.roles[] | select(.name=="MinIO").nodes[].deploy_id'))
How about using something like this stuff below instead? :thinking: 

```
onegate service show -j --extended | jq -r '.SERVICE.roles[]|select(.name=="MinIO").nodes[].vm_info.VM.TEMPLATE.CONTEXT.ETH0_IP'
```

or

```
onegate service show -j --extended | jq -r '.SERVICE.roles[]|select(.name=="MinIO").nodes[].vm_info.VM.TEMPLATE.NIC.IP'
```

You get the same IPs with a single API call, the if you want to do a loop:

```
onegate service show -j --extended | jq -r '.SERVICE.roles[]|select(.name=="MinIO").nodes[].vm_info.VM.TEMPLATE.NIC.IP' | while read IP
; do echo "IP -> $IP"; done
```

2024-10-14 16:23 UTC, rsmontero commented on appliances/MinIO/appliance.sh
> +    msg info "Add MinIO section to fstab"
to fstab?

2024-10-14 16:26 UTC, rsmontero commented on appliances/MinIO/appliance.sh
> +            if [[ ! -d "${local_minio_certs_path}" ]]; then
is this needed? we can just mkdir -p without checking

2024-10-14 16:27 UTC, rsmontero commented on appliances/MinIO/appliance.sh
> +            msg info "Give ownership of /opt/minio to minio-user"
Change ownership of /... to ....

2024-10-14 16:36 UTC, rsmontero commented on appliances/MinIO/appliance.sh
> +    edit_hosts
maybe we do not need a function? or merge the logic of 
```

       # For each node, get IP and create entry using MinIO Multi-Node notation
        i=1
        for node in "${local_nodes[@]}"
        do
            local_ip=$(onegate vm show ${node} --json | jq -r '.VM.TEMPLATE.NIC[].IP')
            local_hosts+="${local_ip} ${local_subdomain}$((i))${local_domain}\n"
            i=$((i + 1))
        done
        msg info "Adding MinIO hostnames to /etc/hosts"
        sed -i "/# End MinIO hosts/i ${local_hosts}" /etc/hosts
```

into the function like setup_etc_hosts

2024-10-15 09:40 UTC, OpenNebulaSupport commented on appliances/MinIO/appliance.sh
> +    msg info "Add MinIO section to fstab"
Copy-paste error :)

2024-10-15 09:40 UTC, Aletibazo commented on appliances/MinIO/appliance.sh
> +    msg info "Add MinIO section to fstab"
Copy-paste error :)

2024-10-15 10:51 UTC, rsmontero approved these changes

2024-10-15 10:55 UTC, merged